global:
  resolve_timeout: 5m

route:
  receiver: 'pagerduty'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'pagerduty'
  pagerduty_configs:
  - service_key: '<PAGERDUTY-INTEGRATION-KEY>'
    severity: 'error'
