apiVersion: v1
kind: Pod
metadata:
  name: golden-signal-calc-pod
  namespace: golden-signal-calc
spec:
  containers:
    - name: app
      image: your-app-image:latest
      ports:
        - containerPort: 80
