apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golden-signal-calc-pvc
  namespace: golden-signal-calc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
