apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rum-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: rum_page_load_seconds
        target:
          type: AverageValue
          averageValue: 2