name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Lint and test
      run: echo "Linting and testing placeholder"

    - name: Build Docker image
      run: |
        docker build -t golden-signal-app:latest .

    - name: Save image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: golden-signal-app-image
        path: /tmp/golden-signal-app.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy Placeholder
      run: echo "Deploy to K8s or Docker registry placeholder"
