# Number of replicas for the deployment
replicaCount: 1

# Container image settings
image:
  repository: myregistry/golden-signal-calculator
  tag: latest
  pullPolicy: IfNotPresent

# Kubernetes service settings
service:
  type: ClusterIP
  port: 3000

# Ingress settings (optional)
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: golden-signal.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Prometheus scraping (optional)
metrics:
  enabled: true
  path: /metrics
  port: 3000
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Node affinity and tolerations (advanced scheduling)
nodeSelector: {}

tolerations: []

affinity: {}

# Custom environment variables for app
env:
  - name: NODE_ENV
    value: production
  - name: LOG_LEVEL
    value: info

# ServiceAccount settings
serviceAccount:
  create: true
  name: ""

# Autoscaling (if you want to enable HPA)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
