---
apiVersion: v1
kind: Namespace
metadata:
  name: golden-signal-calc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: golden-signal-calc-config
  namespace: golden-signal-calc
data:
  APP_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: golden-signal-calc-secret
  namespace: golden-signal-calc
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: golden-signal-calc-sa
  namespace: golden-signal-calc
---
apiVersion: v1
kind: Service
metadata:
  name: golden-signal-calc-service
  namespace: golden-signal-calc
spec:
  selector:
    app: golden-signal-calc
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golden-signal-calc-deployment
  namespace: golden-signal-calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golden-signal-calc
  template:
    metadata:
      labels:
        app: golden-signal-calc
    spec:
      serviceAccountName: golden-signal-calc-sa
      containers:
        - name: app
          image: your-app-image:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: golden-signal-calc-config
            - secretRef:
                name: golden-signal-calc-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /startup
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: golden-signal-calc-hpa
  namespace: golden-signal-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golden-signal-calc-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
