apiVersion: v1
kind: LimitRange
metadata:
  name: golden-signal-calc-limits
  namespace: golden-signal-calc
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 200m
        memory: 256Mi
      type: Container
