apiVersion: v1
kind: Service
metadata:
  name: golden-signal-calc-service
  namespace: golden-signal-calc
spec:
  selector:
    app: golden-signal-calc
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
