CREATE DATABASE pf_keycloak WITH OWNER = postgres TABLESPACE = pg_default CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE pf_keycloak TO postgres;
GRANT TEMPORARY, CONNECT ON DATABASE pf_keycloak TO PUBLIC;
GRANT ALL ON DATABASE pf_keycloak TO postgres;

CREATE DATABASE pf_entity WITH OWNER = postgres TABLESPACE = pg_default CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE pf_entity TO postgres;
GRANT TEMPORARY, CONNECT ON DATABASE pf_entity TO PUBLIC;
GRANT ALL ON DATABASE pf_entity TO postgres;

CREATE DATABASE pf_auth WITH OWNER = postgres TABLESPACE = pg_default CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE pf_auth TO postgres;
GRANT TEMPORARY, CONNECT ON DATABASE pf_auth TO PUBLIC;
GRANT ALL ON DATABASE pf_auth TO postgres;

CREATE DATABASE pf_scheduler WITH OWNER = postgres TABLESPACE = pg_default CONNECTION LIMIT = -1;
GRANT ALL ON DATABASE pf_scheduler TO postgres;
GRANT TEMPORARY, CONNECT ON DATABASE pf_scheduler TO PUBLIC;
GRANT ALL ON DATABASE pf_scheduler TO postgres;