apiVersion: batch/v1
kind: CronJob
metadata:
  name: golden-signal-cron
  namespace: golden-signal-calc
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-task
              image: busybox
              command: ["sh", "-c", "echo Running scheduled task at $(date)"]
          restartPolicy: OnFailure
