apiVersion: apps/v1
kind: Deployment
metadata:
  name: golden-signal-calc-deployment
  namespace: golden-signal-calc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golden-signal-calc
  template:
    metadata:
      labels:
        app: golden-signal-calc
    spec:
      serviceAccountName: golden-signal-calc-sa
      containers:
        - name: golden-signal-calc
          image: your-app-image:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: golden-signal-calc-config
            - secretRef:
                name: golden-signal-calc-secret
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /startup
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 15
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000