apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: golden-signal-calc-db
  namespace: golden-signal-calc
spec:
  serviceName: "db"
  replicas: 2
  selector:
    matchLabels:
      app: golden-signal-db
  template:
    metadata:
      labels:
        app: golden-signal-db
    spec:
      containers:
        - name: db
          image: postgres:14
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
