apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: golden-signal-calc-hpa
  namespace: golden-signal-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golden-signal-calc-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
